on: [pull_request, push, workflow_dispatch]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: per1234/artistic-style-action@v1
        with:
          name-patterns: |
            - '*.cpp'
            - '*.h'
          target-paths: |
            - 'src/'
            - 'examples/'
